module.exports = {
    "hannah abbott": "Hufflepuff student in Harry's year and member of Dumbledore's Army.",
    "bathsheda babbling": "Ancient Runes teacher at Hogwarts",
    "ludo bagman": "Quidditch Beater for the Wimbourne Wasps and Head of the Department of Magical Games and Sports within the Ministry of Magic",
    "bathilda bagshot": "Author of A History of Magic, great aunt of Gellert Grindelwald.",
    "katie bell": "Gryffindor student one year above Harry Potter; Chaser on the Gryffindor Quidditch team.",
    "cuthbert binns": "Ghost, History of Magic professor.",
    "phineas nigellus black": "deceased great-great-grandfather of Sirius Black and former headmaster of Hogwarts, whose painting still hangs in the office and helps out the current headmaster.",
    "regulus arcturus black": "Late brother of Sirius Black, a Death Eater who had turned against Lord Voldemort.",
    "sirius black": "Harry Potter's godfather, a member of the Order of the Phoenix and prisoner on the run.",
    "amelia bones": "Head of the Department of Magical Law Enforcement, aunt of Susan Bones.",
    "susan bones": "Hufflepuff student in Harry's year, a member of Dumbledore's Army.",
    "terry boot": "Ravenclaw student in Harry's year, a member of Dumbledore's Army.",
    "lavender brown": "Gryffindor student in Harry's year, a member of Dumbledore's Army, briefly Ron Weasley's girlfriend.",
    "millicent bulstrode": "Slytherin student in Harry's year, a member of Umbridge's Inquisitorial Squad.",
    "charity burbage": "Professor of Muggle Studies at Hogwarts during Harry's time at school.",
    "frank bryce": "Muggle gardener for the Riddle family.",
    "alecto carrow": "Sister of Amycus Carrow, Death Eater and professor of Muggle Studies for one year, Deputy Headmistress of Hogwarts under Severus Snape",
    "amycus carrow": "Brother of Alecto Carrow, Death Eater and professor of Defence Against the Dark Arts for one year, even though he changed it to just 'Dark Arts', Deputy Headmaster of Hogwarts under Severus Snape",
    "reginald cattermole": "Employee of the Magical Maintenance Department for the Ministry of Magic, impersonated by Ron Weasley",
    "mary cattermole": "Muggle-born wife of Reginald Cattermole, saved by Harry Potter from the Muggle-born Registration Commission.",
    "cho chang": "Ravenclaw student one year above Harry, Quidditch Seeker, member of Dumbledore's Army and Harry's first Love interest",
    "penelope clearwater": "Ravenclaw prefect and girlfriend of Percy Weasley",
    "michael corner": "Ravenclaw student in Harry's year, member of Dumbledore's Army",
    "vincent crabbe, sr.": "Death Eater, father of Vincent Crabbe",
    "vincent crabbe": "Slytherin student in Harry's year, son of Death Eater, Slytherin Quidditch team Beater, a member of the Inquisitorial Squad, a friend of Draco Malfoy.",
    "colin creevey": "Muggle-born Gryffindor student one year below Harry, brother of Dennis Creevey, member of Dumbledore's Army, killed during the Battle of Hogwarts, after sneaking away from the younger evacuated students in the seventh book",
    "dennis creevey": "Muggle-born Gryffindor student three years below Harry, brother of Colin Creevey, member of Dumbledore's Army",
    "dirk cresswell": "Muggle-born Head of the Goblin Liaison Office, went on the run in Deathly Hallows with fellow muggle-born Ted Tonks, Dean Thomas and goblins Gornuk and Griphook.",
    "bartemius crouch, sr.": "Head of the Department of International Magical Cooperation, killed by his son Barty Crouch Jr, Transfigurated into a bone before being buried",
    "barty crouch, sr.": "Head of the Department of International Magical Cooperation, killed by his son Barty Crouch Jr, Transfigurated into a bone before being buried",
    "bartemius crouch, jr.": "Death Eater, credited with facilitating the return of Lord Voldemort, received a Dementor's Kiss, used Polyjuice Potion to impersonate Alastor Moody",
    "barty crouch, jr.": "Death Eater, credited with facilitating the return of Lord Voldemort, received a Dementor's Kiss, used Polyjuice Potion to impersonate Alastor Moody",
    "fleur delacour": "French student who participated in the Triwizard Tournament representing Beauxbatons, later wed Bill Weasley.",
    "gabrielle delacour": "Younger sister of Fleur Delacour, saved by Harry in the Triwizard Tournament",
    "dedalus diggle": "Member of the Order of the Phoenix who took the Dursleys into hiding",
    "amos diggory": "Works for the Department for the Regulation and Control of Magical Creatures, father of Cedric Diggory",
    "cedric diggory": "Hufflepuff student two years above Harry, school prefect, Quidditch Seeker and captain, co-winner of the Triwizard Tournament",
    "elphias doge": "School friend of Albus Dumbledore",
    "antonin dolohov": "Death Eater who killed Fabian Prewett, Gideon Prewett, and Remus Lupin.",
    "aberforth dumbledore": "Brother of Albus and Ariana Dumbledore, owner of the Hog's Head",
    "albus dumbledore": "Hogwarts Headmaster in Harry Potter's time, Transfiguration professor in Tom Riddle's time, founder of the Order of the Phoenix.",
    "dumbledore": "Hogwarts Headmaster in Harry Potter's time, Transfiguration professor in Tom Riddle's time, founder of the Order of the Phoenix.",
    "ariana dumbledore": "Late sister of Albus and Aberforth Dumbledore.",
    "dudley dursley": "Muggle son of Vernon Dursley and Petunia Evans, first cousin of Harry Potter",
    "dudley": "Muggle son of Vernon Dursley and Petunia Evans, first cousin of Harry Potter",
    "marjorie dursley": "Muggle sister of Vernon Dursley, breeds bulldogs, her favourite one named Ripper.",
    "marge dursley": "Muggle sister of Vernon Dursley, breeds bulldogs, her favourite one named Ripper.",
    "petunia dursley": "Harry's aunt, the sister of his mother Lily. Married to Vernon Dursley and mother of Dudley Dursley",
    "petunia": "Harry's aunt, the sister of his mother Lily. Married to Vernon Dursley and mother of Dudley Dursley",
    "vernon dursley": "Harry Potter's muggle uncle, married to his aunt Petunia and father of Dudley Dursley.",
    "vernon": "Harry Potter's muggle uncle, married to his aunt Petunia and father of Dudley Dursley.",
    "marietta edgecombe": "Ravenclaw student one year above Harry, member of Dumbledore's Army",
    "everard": "Former Headmaster of Hogwarts, a particularly famous wizard, whose portrait hangs in many institutions, including the Ministry of Magic",
    "arabella figg": "Squib neighbour of the Dursleys', member of the Order of the Phoenix.",
    "argus filch": "Squib caretaker of Hogwarts",
    "filch": "Squib caretaker of Hogwarts",
    "justin finch-fletchley": "Muggle-born Hufflepuff student in Harry's year, a member of Dumbledore's Army.",
    "seamus finnigan": "Irish Gryffindor student in Harry's year, a member of Dumbledore's Army best friend of Dean Thomas.",
    "seamus": "Irish Gryffindor student in Harry's year, a member of Dumbledore's Army best friend of Dean Thomas.",
    "marcus flint": "Slytherin sixth year Quidditch captain",
    "nicolas flamel": "alchemist, the only known creator of the Philosopher's Stone.",
    "mundungus fletcher": "Common thief and shifty member of the Order of the Phoenix",
    "filius flitwick": "Charms professor at Hogwarts and Head of Ravenclaw",
    "flitwick": "Charms professor at Hogwarts and Head of Ravenclaw",
    "cornelius fudge": "Minister for Magic in the first five books, sacked when he denied Lord Voldemort's return for a year.",
    "fudge": "Minister for Magic in the first five books, sacked when he denied Lord Voldemort's return for a year.",
    "marvolo gaunt": "Pure-blood father of Merope and Morfin Gaunt, grandfather of Tom Marvolo Riddle.",
    "merope gaunt": "Daughter of Marvolo Gaunt, sister of Morfin Gaunt, wife of Tom Riddle Sr, mother of Tom Marvolo Riddle/Lord Voldemort, died after childbirth, named for Merope, one of the Pleiades, who married a mortal[1]",
    "morfin gaunt": "Son of Marvolo Gaunt, brother of Merope Gaunt, uncle of Tom Marvolo Riddle, framed by his nephew for Muggle killings.",
    "anthony goldstein": "Ravenclaw student in Harry's year, member of Dumbledore's Army",
    "goyle sr": "Death Eater, father of Gregory Goyle",
    "gregory goyle": "Slytherin student in Harry's year, Slytherin Quidditch Beater, a member of the Inquisitorial Squad.",
    "goyle": "Slytherin student in Harry's year, Slytherin Quidditch Beater, a member of the Inquisitorial Squad.",
    "hermione granger": "Muggle-born Gryffindor student in Harry's year, one of Harry's best friends, founder of Dumbledore's Army, Gryffindor Prefect",
    "hermione": "Muggle-born Gryffindor student in Harry's year, one of Harry's best friends, founder of Dumbledore's Army, Gryffindor Prefect",
    "gregorovitch": "highly regarded East European wand-maker.",
    "fenrir greyback": "Werewolf, infected Remus Lupin, maimed Bill Weasley and wounded Lavender Brown.",
    "gellert grindelwald": "Dark Wizard, friend, and later rival, of Albus Dumbledore who defeated him in the 1940s.",
    "wilhelmina grubbly-plank": "Substitute Care of Magical Creatures professor during Harry's fourth year",
    "godric gryffindor": "One of the four founders of Hogwarts",
    "rubeus hagrid": "Half-giant keeper of Keys and Grounds at Hogwarts, Care of Magical Creatures professor starting from Harry's third year, a member of the Order of the Phoenix. Once a Hogwarts student, Hagrid was expelled in his third year.",
    "hagrid": "Half-giant keeper of Keys and Grounds at Hogwarts, Care of Magical Creatures professor starting from Harry's third year, a member of the Order of the Phoenix. Once a Hogwarts student, Hagrid was expelled in his third year.",
    "rolanda hooch": "Hogwarts flying instructor, Quidditch referee",
    "mafalda hopkirk": "Witch who works in the Ministry of Magic, impersonated by Hermione Granger in Deathly Hallows.",
    "helga hufflepuff": "One of the four founders of Hogwarts, ancestor of Hepzibah Smith",
    "angelina johnson": "Gryffindor student two years above Harry, Quidditch Chaser and later captain",
    "lee jordan": "Gryffindor student two years above Harry, Hogwarts Quidditch commentator, good friend of Fred and George Weasley at Hogwarts",
    "bertha jorkins": "witch from the Ministry of Magic who was murdered by Voldemort.",
    "igor karkaroff": "Reformed Death Eater, Headmaster of Durmstrang.",
    "viktor krum": "Durmstrang student, Bulgarian Quidditch Seeker, participated in the Triwizard Tournament.",
    "bellatrix lestrange": "Death Eater, sister of Narcissa Malfoy and Andromeda Tonks, cousin of Sirius and Regulus Black, she tortured Frank and Alice Longbottom into insanity.",
    "bellatrix": "Death Eater, sister of Narcissa Malfoy and Andromeda Tonks, cousin of Sirius and Regulus Black, she tortured Frank and Alice Longbottom into insanity.",
    "rabastan lestrange": "Death Eater, brother of Rodolphus Lestrange",
    "rodolphus lestrange": "Death Eater, brother of Rabastan Lestrange, husband of Bellatrix Lestrange",
    "gilderoy lockhart": "Fraudulent celebrity author, Defence Against the Dark Arts teacher.",
    "alice longbottom": "Wife of Frank Longbottom, mother of Neville Longbottom, member of the original Order of the Phoenix, Auror, tortured into insanity by Bellatrix Lestrange along with her husband",
    "augusta longbottom": "Mother of Frank Longbottom and grandmother of Neville Longbottom",
    "frank longbottom": "Father of Neville Longbottom, a member of the original Order of the Phoenix, Auror, tortured into insanity by Bellatrix Lestrange along with his wife.",
    "neville": "Gryffindor student in Harry's year, a member of Dumbledore's Army.",
    "neville longbottom": "Gryffindor student in Harry's year, a member of Dumbledore's Army.",
    "luna lovegood": "Ravenclaw student one year below Harry, a member of Dumbledore's Army.",
    "xenophilius lovegood": "Father of Luna Lovegood, and editor of The Quibbler.",
    "remus lupin": "Gryffindor student before Harry's time, Marauder, a friend of James Potter, werewolf, Professor of Defence Against the Dark Arts in Harry's third year, a member of the Order of the Phoenix.",
    "walden macnair": "The Committee of Disposal of Dangerous Creatures's executioner, also a Death-Eater",
    "draco malfoy": "Slytherin student in Harry's year, Slytherin Quidditch Seeker, school prefect, member of the Inquisitorial Squad, Death Eater",
    "draco": "Slytherin student in Harry's year, Slytherin Quidditch Seeker, school prefect, member of the Inquisitorial Squad, Death Eater",
    "lucius malfoy": "Draco Malfoy's father, an influential Death-Eater, and, early in the series, governor of Hogwarts",
    "lucius": "Draco Malfoy's father, an influential Death-Eater, and, early in the series, governor of Hogwarts",
    "narcissa malfoy": "Lucius Malfoy's wife and Draco Malfoy's mother, sister of Bellatrix Lestrange.",
    "madam malkin": "Clothes shop owner at Diagon Alley",
    "olympe maxime": "Half-giantess, Headmistress of Beauxbatons",
    "ernie macmillan": "Hufflepuff student in Harry's year, school prefect, member of Dumbledore's Army",
    "minerva mcgonagall": "Hogwarts Transfiguration professor, Head of Gryffindor House, Deputy Headmistress of Hogwarts, a member of the Order of the Phoenix.",
    "mcgonagall": "Hogwarts Transfiguration professor, Head of Gryffindor House, Deputy Headmistress of Hogwarts, a member of the Order of the Phoenix.",
    "alastor moody": "Retired Auror, member of the Order of the Phoenix, impersonated by Barty Crouch Jr. in 'The Goblet of Fire'",
    "mad-eye": "Retired Auror, member of the Order of the Phoenix, impersonated by Barty Crouch Jr. in 'The Goblet of Fire'",
    "mad-eye moody": "Retired Auror, member of the Order of the Phoenix, impersonated by Barty Crouch Jr. in 'The Goblet of Fire'",
    "theodore nott": "Slytherin student in the same year as Harry Potter. Nott is one of the few students who can see Thestrals, suggesting that he has witnessed a death at some point. His father is a Death Eater and described as an elderly widower.",
    "garrick ollivander": "Wandmaker, owner of Ollivanders shop.",
    "ollivander": "Wandmaker, owner of Ollivanders shop.",
    "pansy parkinson": "Slytherin student in Harry's year, school prefect, a member of the Inquisitorial Squad, Draco Malfoy's girlfriend for some time.",
    "padma patil": "Ravenclaw student in Harry's year, identical twin sister of Gryffindor Parvati Patil, a member of Dumbledore's Army.",
    "parvati patil": "Gryffindor student in Harry's year, identical twin sister of Ravenclaw Padma Patil, a member of Dumbledore's Army.",
    "peter pettigrew": "Former school friend of James Potter, Sirius Black and Remus Lupin. Betrays James and Lily Potter. Death Eater, an unregistered animagus, Pettigrew is first introduced as a rat known as Scabbers.",
    "pettigrew": "Former school friend of James Potter, Sirius Black and Remus Lupin. Betrays James and Lily Potter. Death Eater, an unregistered animagus, Pettigrew is first introduced as a rat known as Scabbers.",
    "antioch peverell": "Original owner of The Elder Wand in The Tale of the Three Brothers.",
    "cadmus peverell": "Original owner of The Resurrection Stone in The Tale of the Three Brothers",
    "ignotus peverell": "Original owner of The Invisibility Cloak in The Tale of the Three Brothers.",
    "irma pince": "Hogwarts librarian",
    "sturgis podmore": "Member of the Order of the Phoenix, imprisoned in Azkaban",
    "poppy pomfrey": "Hogwarts school nurse",
    "harry potter": "Main character of the series, son of James Potter and Lily Evans, Gryffindor student, Gryffindor Quidditch Seeker and captain, leader of Dumbledore's Army.",
    "harry": "Main character of the series, son of James Potter and Lily Evans, Gryffindor student, Gryffindor Quidditch Seeker and captain, leader of Dumbledore's Army.",
    "james potter": "Harry Potter's father, a member of the Order of the Phoenix, murdered by Lord Voldemort before the series begins.",
    "james": "Harry Potter's father, a member of the Order of the Phoenix, murdered by Lord Voldemort before the series begins.",
    "lily potter": "Harry Potter's mother, a member of the Order of the Phoenix, murdered by Lord Voldemort before the series begins.",
    "lily": "Harry Potter's mother, a member of the Order of the Phoenix, murdered by Lord Voldemort before the series begins.",
    "ernest 'ernie' prang": "(fl. 1993-1997), also called Ern by Stanley Shunpike, was the driver of the Knight Bus.",
    "ernie": "(fl. 1993-1997), also called Ern by Stanley Shunpike, was the driver of the Knight Bus.",
    "quirinus quirrell": "Defence Against the Dark Arts professor in Harry's first year, possessed by Lord Voldemort in Philosopher's Stone.",
    "quirrell": "Defence Against the Dark Arts professor in Harry's first year, possessed by Lord Voldemort in Philosopher's Stone.",
    "helena ravenclaw/the grey lady": "Daughter of Rowena Ravenclaw, stole her mother's diadem and hid it, killed by the Bloody Baron and became Ravenclaw's house ghost.",
    "rowena ravenclaw": "Co-founder of Hogwarts, mother of Helena Ravenclaw",
    "mary riddle": "Muggle wife of Thomas Riddle, mother of Tom Riddle Sr, mother-in-law of Merope Gaunt, grandmother of Tom Marvolo Riddle/Lord Voldemort, killed by her grandson",
    "thomas riddle": "Muggle husband of Mary Riddle, father of Tom Riddle Sr, grandfather of Tom Marvolo Riddle/Lord Voldemort, killed by his grandson.",
    "tom riddle sr": "Muggle husband of Merope Gaunt, father of Tom Marvolo Riddle/Lord Voldemort, son of Thomas and Mary Riddle, killed by his son",
    "tom marvolo riddle": "The villain of the series, the murderer of Harry Potter's parents and many others in his quest for immortality and absolute power",
    "tom riddle": "The villain of the series, the murderer of Harry Potter's parents and many others in his quest for immortality and absolute power",
    "demelza robins": "a student at Hogwarts School of Witchcraft and Wizardry, sorted into Gryffindor House. She was a Chaser for the Gryffindor Quidditch team, and was noted to be particularly skilled at dodging Bludgers.",
    "augustus rookwood": "Death Eater, spy working in the Department of Mysteries",
    "albert runcorn": "was a Ministry of Magic employee of high rank during the administration under Pius Thicknesse. His chief function was an investigator of alleged Muggle-borns.",
    "scabior": "Snatcher who captures Harry Potter, Ron Weasley and Hermione Granger in Deathly Hallows.",
    "newt scamander": "Author of Fantastic Beasts and Where to Find Them, among other books. Headmaster and, Hufflepuff student at Hogwarts.",
    "rufus scrimgeour": "Head of the Auror Office, replaces Cornelius Fudge as Minister for Magic.",
    "kingsley shacklebolt": "Auror, replaces Pius Thicknesse as Minister for Magic, member of the Order of the Phoenix",
    "stan shunpike": "Conductor of the Knight Bus, later jailed in Azkaban on suspicions of being a death-eater.",
    "aurora sinistra": "Professor and member of the Astronomy Department at Hogwarts, a witch with dark skin, hair, and eyes.",
    "rita skeeter": "Reporter for the Daily Prophet, author of The Life and Lies of Albus Dumbledore, unregistered animagus.",
    "horace slughorn": "Former Potions professor at Hogwarts and Head of Slytherin House who taught Tom Marvolo Riddle and returns to Hogwarts in Harry's sixth year.",
    "slughorn": "Former Potions professor at Hogwarts and Head of Slytherin House who taught Tom Marvolo Riddle and returns to Hogwarts in Harry's sixth year.",
    "salazar slytherin": "Co-founder of Hogwarts, Parseltongue, ancestor of the Gaunt family and Lord Voldemort.",
    "salazar": "Co-founder of Hogwarts, Parseltongue, ancestor of the Gaunt family and Lord Voldemort.",
    "hepzibah smith": "Elderly, wealthy antique collector, descendant of Helga Hufflepuff, murdered and robbed by Tom Marvolo Riddle",
    "zacharias smith": "Hufflepuff student, a member of Dumbledore's Army.",
    "severus snape": "Hogwarts, Potions and later Defence Against the Dark Arts professor, Head of Slytherin House, a member of both the Death Eaters and the Order of the Phoenix.",
    "snape": "Hogwarts, Potions and later Defence Against the Dark Arts professor, Head of Slytherin House, a member of both the Death Eaters and the Order of the Phoenix.",
    "alicia spinnet": "Chaser on the Gryffindor Quidditch team, two years above Harry Potter at Hogwarts. Member of Dumbledore's Army.",
    "pomona sprout": "Hogwarts Herbology professor, Head of Hufflepuff House.",
    "pius thicknesse": "Minister for Magic while under the Imperius Curse, later replaced by Kingsley Shacklebolt.",
    "dean thomas": "Gryffindor student in Harry's year, a member of Dumbledore's Army, briefly Ginny Weasley's boyfriend, Gryffindor Quidditch Chaser.",
    "andromeda tonks": "Sister of Bellatrix Lestrange and Narcissa Malfoy, disowned by her family for marrying Muggle-born Ted Tonks, mother of Nymphadora Tonks.",
    "nymphadora tonks": "Daughter of Ted and Andromeda Tonks, Auror and member of the Order of the Phoenix. She marries Remus Lupin, and become the mother of Teddy Lupin.",
    "ted tonks": "Muggle-born husband of Andromeda and father of Nymphadora Tonks.",
    "travers": "was a wizard and a Death Eater. Escaped from Azkaban after Lord Voldemort's return.",
    "sybill patricia trelawney": "Hogwarts Divination professor, predicted the prophecy that prompted Lord Voldemort to go after the Potters",
    "dolores jane umbridge": "Senior Undersecretary to the Minister for Magic, Defence Against the Dark Arts professor, Hogwarts High Inquisitor, Headmistress of Hogwarts, who enthusiastically joins in the persecution of half-bloods under Voldermort.",
    "dolores umbridge": "Senior Undersecretary to the Minister for Magic, Defence Against the Dark Arts professor, Hogwarts High Inquisitor, Headmistress of Hogwarts, who enthusiastically joins in the persecution of half-bloods under Voldermort.",
    "umbridge": "Senior Undersecretary to the Minister for Magic, Defence Against the Dark Arts professor, Hogwarts High Inquisitor, Headmistress of Hogwarts, who enthusiastically joins in the persecution of half-bloods under Voldermort.",
    "emmeline vance": "a member of the party that brings Harry to Grimmauld Place, a member of the Order of the Phoenix. Described as 'A stately looking witch in an emerald green shawl'.",
    "romilda vane": "Hogwarts student who tried to romance Harry with Chocolate Cauldrons containing a love potion from Weasley's Wizard Wheezes",
    "septima vector": "Arithmancy professor at Hogwarts.",
    "lord voldemort": "The villain of the series, the murderer of Harry Potter's parents and many others in his quest for immortality and absolute power.",
    "voldemort": "The villain of the series, the murderer of Harry Potter's parents and many others in his quest for immortality and absolute power.",
    "arthur weasley": "Muggle-obsessed Ministry of Magic employee. Husband of Molly Weasley, father of Bill, Charlie, Percy, Fred, George, Ron, and Ginny Weasley, member of the Order of the Phoenix",
    "arthur": "Muggle-obsessed Ministry of Magic employee. Husband of Molly Weasley, father of Bill, Charlie, Percy, Fred, George, Ron, and Ginny Weasley, member of the Order of the Phoenix",
    "bill weasley": "Oldest son of Arthur and Molly Weasley, Gringotts employee.",
    "charlie weasley": "Second son of Arthur and Molly Weasley, and a member of the Order of the Phoenix, works with dragons in Romania.",
    "fred weasley": "Son of Arthur and Molly Weasley and identical twin brother of George Weasley, a member of Dumbledore's Army, Gryffindor Quidditch Beater, co-owner of Weasleys' Wizard Wheezes, killed in an explosion caused by Augustus Rookwood in the Battle of Hogwarts.",
    "fred": "Son of Arthur and Molly Weasley and identical twin brother of George Weasley, a member of Dumbledore's Army, Gryffindor Quidditch Beater, co-owner of Weasleys' Wizard Wheezes, killed in an explosion caused by Augustus Rookwood in the Battle of Hogwarts.",
    "george weasley": "Son of Arthur and Molly Weasley and identical twin brother of Fred Weasley, member of Dumbledore's Army, Gryffindor Quidditch Beater, co-owner of Weasleys' Wizard Wheezes, marries Angelina Johnson",
    "george": "Son of Arthur and Molly Weasley and identical twin brother of Fred Weasley, member of Dumbledore's Army, Gryffindor Quidditch Beater, co-owner of Weasleys' Wizard Wheezes, marries Angelina Johnson",
    "ginny weasley": "Only daughter and youngest child of Arthur and Molly Weasley, Gryffindor student one year under Harry, Gryffindor Quidditch Seeker and Chaser, a member of Dumbledore's Army.",
    "ginny": "Only daughter and youngest child of Arthur and Molly Weasley, Gryffindor student one year under Harry, Gryffindor Quidditch Seeker and Chaser, a member of Dumbledore's Army.",
    "molly weasley": "Wife of Arthur Weasley, mother of Bill, Charlie, Percy, Fred, George, Ron and Ginny Weasley, a member of the Order of the Phoenix.",
    "molly": "Wife of Arthur Weasley, mother of Bill, Charlie, Percy, Fred, George, Ron and Ginny Weasley, a member of the Order of the Phoenix.",
    "percy weasley": "Third son of Arthur and Molly Weasley, Gryffindor prefect and Head Boy then Ministry of Magic employee, long estranged from his family before joining them against the Death Eaters in Deathly Hallows,",
    "percy": "Third son of Arthur and Molly Weasley, Gryffindor prefect and Head Boy then Ministry of Magic employee, long estranged from his family before joining them against the Death Eaters in Deathly Hallows,",
    "ron weasley": "Harry's close friend, youngest Son of Arthur and Molly Weasley, Gryffindor Quidditch Keeper, school prefect, a member of Dumbledore's Army.",
    "ron": "Harry's close friend, youngest Son of Arthur and Molly Weasley, Gryffindor Quidditch Keeper, school prefect, a member of Dumbledore's Army.",
    "oliver wood": "Hogwarts student, Gryffindor Quidditch Keeper and captain.",
    "kennilworthy whisp": "author of 'Quidditch Through the Ages'",
    "yaxley": "Death Eater, Head of Magical Law Enforcement under Voldemort's regime.",
    "blaise zabini": "Slytherin student in Harry's year, friends with Draco Malfoy.",
    "aragog": "Acromantula raised by Rubeus Hagrid, lives in the Forbidden Forest.",
    "bane": "Centaur, not very wizard-friendly.",
    "beedle the bard": "Author of several Wizarding fairy tales, including The Tale of the Three Brothers",
    "the bloody baron": "Slytherin House ghost, suitor and killer of Helena Ravenclaw, killed himself in remorse",
    "buckbeak": "Hippogriff belonging at various times to Rubeus Hagrid, Sirius Black and Harry Potter",
    "sir cadogan": "Armoured and somewhat mad knight occupying a painting in Hogwarts",
    "crookshanks": "Intelligent cat belonging to Hermione Granger.",
    "dobby": "House-elf originally belonging to the Malfoy family, which Harry helps set free in Chamber of Secrets. He becomes the only paid house-elf at Hogwarts.",
    "enid": "Great-aunt of Neville Longbottom.",
    "errol": "Owl belonging to the Weasley family",
    "fang": "Boarhound belonging to Rubeus Hagrid.",
    "the fat friar": "Hufflepuff House ghost.",
    "fridwulfa": "Female giant, mother of Grawp and Hagrid according to the Daily Prophet.",
    "the fat lady": "Witch in the painting that conceals the entrance to the Gryffindor common room.",
    "fawkes": "Phoenix belonging to Albus Dumbledore, saved Harry Potter from Basilisk in the Chamber of Secrets.",
    "firenze": "Centaur, professor of Divination at Hogwarts.",
    "fluffy": "Three-headed dog belonging to Rubeus Hagrid, protector of the Philosopher's Stone.",
    "grawp": "Giant, half-brother of Rubeus Hagrid",
    "griphook": "Goblin, works at Gringotts Bank which he helps Harry and his friends Steal the cup from within the Lestrange vault.",
    "hedwig": "Harry Potter's pet owl",
    "hokey": "House-elf belonging to Hepzibah Smith",
    "kreacher": "House-elf belonging to the Black family, and later Harry Potter. Though at first preferring to serve the pureblood line (including Regulus Black, Narcissa Malfoy, Bellatrix Lestrange, and Draco Malfoy), he eventually likes serving under Harry as he treats him better.",
    "magorian": "Centaur.",
    "moaning myrtle": "Muggle-born Ravenclaw student during Tom Marvolo Riddle's time at Hogwarts, killed by the Basilisk in a girl's bathroom, which she continues to haunt.",
    "mrs norris": "Cat belonging to Argus Filch",
    "great aunt muriel": "Great aunt of the Weasley children",
    "nagini": "Lord Voldemort's giant pet snake, which does his bidding. One of Voldemort's Horcruxes.",
    "nearly headless nick": "Gryffindor House ghost, once Sir Nicholas de Mimsy-Porpington.",
    "norbert/norberta": "Dragon belonging to Rubeus Hagrid, later secretly moved to the Dragon Reserve in Romania by friends of Charlie Weasley.",
    "peeves": "Hogwarts poltergeist, a mischievous magical creature.",
    "pigwidgeon": "Scops Owl belonging to Ron Weasley",
    "madam rosmerta": "Proprietor of the Three Broomsticks in Hogsmeade",
    "ronan": "Centaur living in the Forbidden Forest",
    "scabbers": "Ron Weasley's pet rat in the first three stories. He is revealed at the end of Prisoner of Azkaban to be a wizard in animal form: 'Peter Pettigrew.'",
    "trevor": "Toad belonging to Neville Longbottom",
    "winky": "A female house elf who originally belonged to Bartemius Crouch Sr., but was sacked by him when evidence emerged that she had used magic at The Quidditch World Cup"
};
